version: 1.0.{build}
build:
  project: Launcher\Launcher.sln
  verbosity: normal
  
before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
  
configuration:
  - Release
  
after_test:
  - md LauncherRelease
  - md LauncherRelease\de-DE
  - xcopy "%CD%\Launcher\Launcher\bin\Release\*.exe" "%CD%\LauncherRelease" /y
  - xcopy "%CD%\Launcher\Launcher\bin\Release\*.dll" "%CD%\LauncherRelease" /y
  - xcopy "%CD%\Launcher\Launcher\bin\Release\de-DE\OpenRCT2 Launcher.resources.dll" "%CD%\LauncherRelease\de-DE" /y
  
artifacts:
  - path: LauncherRelease
