version: 1.0.{build}
build:
  project: Launcher\Launcher.sln
  verbosity: normal
  
configuration:
  - Release
  
after_test:
  - md LauncherRelease
  - xcopy "%CD%\Launcher\Launcher\bin\Release\*.exe" "%CD%\LauncherRelease" /y
  - xcopy "%CD%\Launcher\Launcher\bin\Release\*.dll" "%CD%\LauncherRelease" /y
  - xcopy "%CD%\Launcher\Launcher\bin\Release\de-DE\*.dll" "%CD%\LauncherRelease\de-DE" /y
  
artifacts:
  - path: LauncherRelease
