'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Launcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property cat_paw() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cat_paw", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complete.
        '''</summary>
        Friend ReadOnly Property common_complete() As String
            Get
                Return ResourceManager.GetString("common_complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Error has occured!.
        '''</summary>
        Friend ReadOnly Property common_errorOccurred() As String
            Get
                Return ResourceManager.GetString("common_errorOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saves moved to folder and Linked!.
        '''</summary>
        Friend ReadOnly Property extras_anyFolderSync_done() As String
            Get
                Return ResourceManager.GetString("extras_anyFolderSync_done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The folder you selected doesn&apos;t exist!.
        '''</summary>
        Friend ReadOnly Property extras_anyFolderSync_error_notexists() As String
            Get
                Return ResourceManager.GetString("extras_anyFolderSync_error_notexists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select where you want the saves to be stored..
        '''</summary>
        Friend ReadOnly Property extras_anyFolderSync_fileDialog_desc() As String
            Get
                Return ResourceManager.GetString("extras_anyFolderSync_fileDialog_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to move your saves to a new folder?.
        '''</summary>
        Friend ReadOnly Property extras_anyFolderSync_firstWarning_text() As String
            Get
                Return ResourceManager.GetString("extras_anyFolderSync_firstWarning_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure?.
        '''</summary>
        Friend ReadOnly Property extras_anyFolderSync_firstWarning_title() As String
            Get
                Return ResourceManager.GetString("extras_anyFolderSync_firstWarning_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Done! You&apos;re all good to go!.
        '''</summary>
        Friend ReadOnly Property extras_cdSoundtrack_done_text() As String
            Get
                Return ResourceManager.GetString("extras_cdSoundtrack_done_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to copy file - Do you have the CD inserted and the game installed?
        '''
        '''Exact Error:
        '''.
        '''</summary>
        Friend ReadOnly Property extras_cdSoundtrack_failed_text() As String
            Get
                Return ResourceManager.GetString("extras_cdSoundtrack_failed_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you are using a CD to run RollerCoaster Tycoon 1, Please insert it now..
        '''</summary>
        Friend ReadOnly Property extras_cdSoundtrack_firstWarning_text() As String
            Get
                Return ResourceManager.GetString("extras_cdSoundtrack_firstWarning_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please insert RCT 1 CD.
        '''</summary>
        Friend ReadOnly Property extras_cdSoundtrack_firstWarning_title() As String
            Get
                Return ResourceManager.GetString("extras_cdSoundtrack_firstWarning_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show File Locations (Debug).
        '''</summary>
        Friend ReadOnly Property extras_fileLocationsButton_text() As String
            Get
                Return ResourceManager.GetString("extras_fileLocationsButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file you are looking for is CSS17.dat.
        '''</summary>
        Friend ReadOnly Property extras_fileSoundtrack_hint() As String
            Get
                Return ResourceManager.GetString("extras_fileSoundtrack_hint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No file selected..
        '''</summary>
        Friend ReadOnly Property extras_fileSoundtrack_noFileSelected() As String
            Get
                Return ResourceManager.GetString("extras_fileSoundtrack_noFileSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add RCT 1 Title Music.
        '''</summary>
        Friend ReadOnly Property extras_rct1musicButton_text() As String
            Get
                Return ResourceManager.GetString("extras_rct1musicButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add RCT1 Title Music from File.
        '''</summary>
        Friend ReadOnly Property extras_rct1musicFileButton_text() As String
            Get
                Return ResourceManager.GetString("extras_rct1musicFileButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The launcher could not find the registry keys. Do you have Both RCT1 &amp; RCT2 Installed? If you do, please open an issue on GitHub..
        '''</summary>
        Friend ReadOnly Property extras_setupReg_noRegisterKeys() As String
            Get
                Return ResourceManager.GetString("extras_setupReg_noRegisterKeys", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to move your Saves to Dropbox?.
        '''</summary>
        Friend ReadOnly Property extras_syncDropbox_firstWarning_text() As String
            Get
                Return ResourceManager.GetString("extras_syncDropbox_firstWarning_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Move Saves?.
        '''</summary>
        Friend ReadOnly Property extras_syncDropbox_firstWarning_title() As String
            Get
                Return ResourceManager.GetString("extras_syncDropbox_firstWarning_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saves moved to Dropbox and Linked!.
        '''</summary>
        Friend ReadOnly Property extras_syncDropbox_moved_text() As String
            Get
                Return ResourceManager.GetString("extras_syncDropbox_moved_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saves Moved!.
        '''</summary>
        Friend ReadOnly Property extras_syncDropbox_moved_title() As String
            Get
                Return ResourceManager.GetString("extras_syncDropbox_moved_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sorry, I don&apos;t think you have Dropbox Installed..
        '''</summary>
        Friend ReadOnly Property extras_syncDropbox_notInstalled() As String
            Get
                Return ResourceManager.GetString("extras_syncDropbox_notInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sync Saves to Any Folder.
        '''</summary>
        Friend ReadOnly Property extras_syncSavesAnyFolderButton_text() As String
            Get
                Return ResourceManager.GetString("extras_syncSavesAnyFolderButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sync Saves to Dropbox.
        '''</summary>
        Friend ReadOnly Property extras_syncSavesDropboxButton_text() As String
            Get
                Return ResourceManager.GetString("extras_syncSavesDropboxButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extras.
        '''</summary>
        Friend ReadOnly Property extras_title() As String
            Get
                Return ResourceManager.GetString("extras_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extra&apos;s.
        '''</summary>
        Friend ReadOnly Property frmLauncher_extrasButton_text() As String
            Get
                Return ResourceManager.GetString("frmLauncher_extrasButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Force Update.
        '''</summary>
        Friend ReadOnly Property frmLauncher_forceUpdateButton_text() As String
            Get
                Return ResourceManager.GetString("frmLauncher_forceUpdateButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OpenRCT2 not installed or not found! Downloading. When it is done, feel free to press play again..
        '''</summary>
        Friend ReadOnly Property frmLauncher_launchGame_RCT2NotFound() As String
            Get
                Return ResourceManager.GetString("frmLauncher_launchGame_RCT2NotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating due to Missing Files....
        '''</summary>
        Friend ReadOnly Property frmLauncher_launchGame_updateMessage() As String
            Get
                Return ResourceManager.GetString("frmLauncher_launchGame_updateMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Launch OpenRCT2.
        '''</summary>
        Friend ReadOnly Property frmLauncher_launchGameButton_text() As String
            Get
                Return ResourceManager.GetString("frmLauncher_launchGameButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Have you installed and ran RCT2 at least once? If not, then please do so and try again..
        '''</summary>
        Friend ReadOnly Property frmLauncher_Load_neverRun() As String
            Get
                Return ResourceManager.GetString("frmLauncher_Load_neverRun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log Output to File.
        '''</summary>
        Friend ReadOnly Property frmLauncher_logButton_text() As String
            Get
                Return ResourceManager.GetString("frmLauncher_logButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OpenRCT2 Launcher.
        '''</summary>
        Friend ReadOnly Property frmLauncher_title() As String
            Get
                Return ResourceManager.GetString("frmLauncher_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Force updating....
        '''</summary>
        Friend ReadOnly Property frmLauncher_update_forceUpdate() As String
            Get
                Return ResourceManager.GetString("frmLauncher_update_forceUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating....
        '''</summary>
        Friend ReadOnly Property frmLauncher_updateStateMessage_updating() As String
            Get
                Return ResourceManager.GetString("frmLauncher_updateStateMessage_updating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Up to Date!.
        '''</summary>
        Friend ReadOnly Property frmLauncher_updateStateMessage_uptodate() As String
            Get
                Return ResourceManager.GetString("frmLauncher_updateStateMessage_uptodate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking if you are up to date....
        '''</summary>
        Friend ReadOnly Property frmLauncher_updateStatus_baseText() As String
            Get
                Return ResourceManager.GetString("frmLauncher_updateStatus_baseText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verbose Output.
        '''</summary>
        Friend ReadOnly Property frmLauncher_verboseOutputButton_text() As String
            Get
                Return ResourceManager.GetString("frmLauncher_verboseOutputButton_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rollercoaster_tycoon_2_001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rollercoaster_tycoon_2_001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
