//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LauncherWPF.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LauncherWPF.Resources.Text.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string UI_WINDOWS_GENERAL_CONFIRM {
            get {
                return ResourceManager.GetString("UI_WINDOWS_GENERAL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates.
        /// </summary>
        public static string UI_WINDOWS_WELCOME_AUTOUPDATE {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_AUTOUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re going to setup a few basic settings for the launcher to use. These can be changed anytime you wish under the Settings button on the main form..
        /// </summary>
        public static string UI_WINDOWS_WELCOME_CONFIGURATION {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Folder:.
        /// </summary>
        public static string UI_WINDOWS_WELCOME_DOWNLOAD_BLOCK {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_DOWNLOAD_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the launcher discovers that a build of OpenRCT2 is ready to download, this is the folder that the build is downloaded to..
        /// </summary>
        public static string UI_WINDOWS_WELCOME_DOWNLOAD_BLOCK_TOOLTIP {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_DOWNLOAD_BLOCK_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Folder:.
        /// </summary>
        public static string UI_WINDOWS_WELCOME_EXTRACT_BLOCK {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_EXTRACT_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the folder that a build will be extracted to..
        /// </summary>
        public static string UI_WINDOWS_WELCOME_EXTRACT_BLOCK_TOOLTIP {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_EXTRACT_BLOCK_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! This appears to be your first time running the OpenRCT2 Launcher. This won&apos;t take very long to get underway.
        ///
        ///Here are the actions I&apos;m going to perform:
        ///	1) I&apos;m going to try and locate Roller Coaster Tycoon 2. If I can&apos;t find it, you&apos;ll have to tell me where it is. This is VERY important to get right!
        ///	2) I&apos;m going to generate a bunch of OpenRCT2 directories inside of &quot;Documents&quot;.
        ///	3) I&apos;m going to download the latest version of OpenRCT2.
        ///If you are OK with this, press &quot;OK&quot; below. If you a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UI_WINDOWS_WELCOME_HELLO {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCT2 Folder:.
        /// </summary>
        public static string UI_WINDOWS_WELCOME_RCT2_BLOCK {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_RCT2_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path where Roller Coaster Tycoon 2 is installed..
        /// </summary>
        public static string UI_WINDOWS_WELCOME_RCT2_BLOCK_TOOLTIP {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_RCT2_BLOCK_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Configuration.
        /// </summary>
        public static string UI_WINDOWS_WELCOME_TAB_HEADER_CONFIGURATION {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_TAB_HEADER_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string UI_WINDOWS_WELCOME_TAB_HEADER_GETTING_STARTED {
            get {
                return ResourceManager.GetString("UI_WINDOWS_WELCOME_TAB_HEADER_GETTING_STARTED", resourceCulture);
            }
        }
    }
}
